### ISSUE TITLE
Change equalizer settings after enable/disabling the microphone causes a crash

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#100]
I believe this might have been fixed in your branch @atyrrell1

**Comment by atyrrell1** [comment]
I can confirm that this does not crash for me. The fix will be included in my next PR.

**Comment by atyrrell1** [comment]
Fixed in commit Fixed Equalizer Recording Issue in MicrophonePlayerAdapter: commit 7c89a8c86e0f00a185935860b095eb9226b11529
