### ISSUE TITLE
Removing a preset will apply it on the Default

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#101]
1. Have 2 presets where one is the Default preset. Ensure that they both have different settings.

2. Remove the preset that is not the Default preset.

3. Notice that the Default preset is using the same preset settings as the one that was deleted.

**Comment by atyrrell1** [comment]
Caught and fixed yesterday when I was writing the UI tests.

**Comment by atyrrell1** [comment]
Fixed in add and remove equalizer preset test commit  (commit 47376e000b835c26f6036080b19f4e1c0c0cdfad)
