### ISSUE TITLE
Microphone Player Adapter Not Ready in Initial State

### ISSUE THREAD

**Issue by atyrrell1** [ECE493-Group5/adjustable-audio#110]
To Reproduce:

1. Install application
2. Grant Permissions
3. Navigate to Microphone Player Adapter
4. Press Microphone Button

- Notice that the microphone button doesn't change colour and therefore the microphone doesn't turn on

**Comment by rizwan146** [comment]
Hmm, I can try to continuously reset the microphone to force it to be ready.

**Comment by atyrrell1** [comment]
What about removing the return statement on Line 68?

**Comment by rizwan146** [comment]
Unfortunately that will not work because the initialization of the AudioRecord and AudioTrack can fail, (though this is a rare case).

**Comment by rizwan146** [comment]
I think our best bet is to call startRecording() again just before the return statement (after maybe a 250 ms delay if its too much for the Android phone to handle).

**Comment by atyrrell1** [comment]
I think it's fixed in this commit: Force restart audio recording to fix #109 (commit 5b7c5bdc8352fde7f180aaa713fc7a742829931b)
