### ISSUE TITLE
Another song in the playlist does not get selected when the currently selected song gets removed.

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#19]
Steps to reproduce:
1. Add two songs to the playlist
2. Remove the first song (which automatically gets selected)
3. Notice that the second song does not get selected in the playlist

However, notice that this works:
1. Add two songs to the playlist
2. Select the second song
3. Remove the second song
4. Notice that the first song gets selected.

**Comment by atyrrell1** [comment]
Additionally, selecting a song in the queue does not play that song. The song continues. I'm not sure if this is a bug or just something not implemented yet.

**Comment by atyrrell1** [comment]
I think this is the commit that fixed it: Fixing bugs related to skipping song while playing and removing song while playing (commit c2583c43ddb76a493c74b2034061646f12000fa9)
