### ISSUE TITLE
Permissions not handled correctly

### ISSUE THREAD

**Issue by atyrrell1** [ECE493-Group5/adjustable-audio#67]
We only check for the read and write external storage. We don't check for the rest of the permissions. This caused an issue on the emulator when only those permissions were enabled, the microphone service crashed and the app failed.

**Comment by atyrrell1** [comment]
I don't know if the hearing test requires any of these permissions, so I included Stephen as well. We don't handle when permissions are denied

**Comment by atyrrell1** [comment]
I know Rizwan is requesting the microphone permission in the microphone fragment. However, the microphone service starts in the main activity and it seems the microphone permission is needed to create the AudioRecord in the service.

**Comment by rizwan146** [comment]
We can try to move all the permission requesting logic into the main activity and start the services when the required permissions are granted.

**Comment by atyrrell1** [comment]
Yea that’s what I was thinking. I wanted to communicate to everybody what
the issue is so nobody gets angry with me later for changing their stuff.

**Comment by atyrrell1** [comment]
If someone gets to it before me, I won’t be upset about it.
