### ISSUE TITLE
1.2.2.3 Access audio stored on the phone

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#7]

**Comment by rizwan146** [comment]
@atyrrell1 Hows your progress on the MediaBrowserService going? Seems like I need this class to initialize MediaBrowser on the client side. Is it safe to merge your progress into my working branch (eg. not master)?

**Comment by atyrrell1** [comment]
Theoretically it's safe, however I can't test anything to check if it is working

**Comment by rizwan146** [comment]
I've merge what you had so far into my current branch. It seems like I need to implement the onGetRoot method and onLoadChildren method to continue my work. I'll do that unless you're already working on it?

**Comment by rizwan146** [comment]
I think I have a working implementation for onGetRoot and onLoadChildren but its difficult to test. Feel free to merge my branch into yours.

Also we need to figure out how we are going to display the queue of music on the MediaPlayerFragment.

**Comment by atyrrell1** [comment]
I think I have a way of integrating the two sides which I'm going to implement it because I want to test the media player's functionality this afternoon. I can clean it up later if we need to
