### ISSUE TITLE
Changing global volume is not displayed correctly on UI and after switching fragments

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#75]
Steps to reproduce:

- switch to the settings fragment
- change global volume to 100%
- switch out of settings fragment
- switch back into settings fragment
- notice that the global volume is no longer 100%

**Comment by atyrrell1** [comment]
90% sure that this is because there is a conversion that isn't happening

**Comment by rizwan146** [comment]
I'll have a fix for this in my next PR.
