### ISSUE TITLE
Playing music after performing hearing test crashes the program

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#76]
![image](https://user-images.githubusercontent.com/23422487/77716516-02c4e800-6fa4-11ea-939e-0542ce785533.png)

It seems to be related to the audio focus logic. Any ideas?

**Comment by szuk1** [comment]
Thats my issue, and I know exactly whats doing it! Ill fix it quick

**Comment by szuk1** [comment]
fixed with b3ef2f8edb07e84675864ddee686a9817bb1c168
