### ISSUE TITLE
Changing the global volume causes audio balance to work for only 1 side

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#99]

**Comment by rizwan146** [comment]
I've concluded that this problem only occurs on the Pixel 2. I have a work around but its not great. I think this is a bug with the emulator.

**Comment by atyrrell1** [comment]
So it doesn’t occur on your actual phone?

**Comment by szuk1** [comment]
I ran into some issues with Pixel2/Pixel3 with setting volumes as well. Might be a bug with their emulator

**Comment by rizwan146** [comment]
I just tested on my phone and there are no issues. Nexus 4 is also working.
Anyways, I do have a workaround but it might annoy the user.

**Comment by szuk1** [comment]
How does the workaround work?

**Comment by rizwan146** [comment]
Basically, whenever the global volume changes, I restart the equalizer and everything works again. However, restarting the equalizer too frequently can cause really weird audio "breaking" noises. So the equalizer restarts 1 second after the global volume is changed. This 1 second delay can be annoying for a user.

**Comment by atyrrell1** [comment]
Can I see the workaround? I'm a little confused why restarting the equalizer would work

**Comment by szuk1** [comment]
Ah, yeah that's a really frustrating bug to deal with. I'm glad we have some sort of a solution for it though, thanks Rizwan!

**Comment by rizwan146** [comment]
The specific commit is:
https://github.com/ECE493-Group5/adjustable-audio/commit/34762a29311c99b5311801d28b2076fa6c0fbd88
